### ISSUE TITLE
No output being created - are there any log files that can be made to identify error?

### ISSUE THREAD

**Issue by Krutik6** [furkanmtorun/gnomad_python_api#9]
Dear Developer,

I really like the novel idea of creating an API for gnomad, and hope I can make use of this tool.

I am just trying to run the example commands within the `gnomad_python_api` folder, however, I am unable to get any data in the output folder. 

`python3 gnomad_api_cli.py -filter_by=gene_name -search_by="BRCA1" -dataset="gnomad_r2_1" -sv_dataset="gnomad_sv_r2_1"` 

I am using python 3.8. Do you have any .log files that can be created to locate where any potential bugs may be?

Many thanks,
Krutik

**Comment by furkanmtorun** [comment]
Dear Krutik,

Thanks for reaching out to me!
The gnomAD team made several updates on their API service. So, the query syntaxes in my code should be corrected according to up-to-date versions. So, I believe that if the GraphQL queries within the code are updated, it can continue serving. Since I am currently not able to do the required changes, it would be so great if you can send a PR.

Also, you could give a try the R version by @daynefiler : https://github.com/daynefiler/gnomadR

Best,
Furkan
